server:
  port: 8080
  servlet:
    context-path: /product/analyse/v1

spring:
  application:
    name: product-analyse
  datasource:
    url: jdbc:mysql://localhost:3306/product-analyse?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
config:
  allowed-ips:
    - 127.0.0.1
    - 0:0:0:0:0:0:0:1


springdoc:
  swagger-ui:
    urlsPrimaryName: public-config
